location /slhrm {
    alias /home/frappe/frappe-bench/sites/slhrm_pwa;
    try_files $uri $uri/ /slhrm/index.html;

    location ~* \.(?:css|js|woff2?|ttf|eot|ico|svg|gif|jpe?g|png|webp|map)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
